services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: db01
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PG_CONN_URL: user:password@pg/db01
    entrypoint: ./prestart.sh
    command:
      - gunicorn
      - main:app
      - --workers
      - "1"
      - --worker-class
      - uvicorn.workers.UvicornWorker
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy


